# Generated by Django 3.2.10 on 2022-11-17 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appNegative', '0002_coment_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coment',
            options={'ordering': ['-created']},
        ),
        migrations.RenameField(
            model_name='coment',
            old_name='timestamp',
            new_name='created',
        ),
    ]
