# Generated by Django 3.2.10 on 2022-11-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appNegative', '0003_auto_20221117_1230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coment',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='coment',
            name='created',
        ),
        migrations.AddField(
            model_name='coment',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='logo_perfil.png', upload_to=''),
        ),
    ]
