# Generated by Django 3.2.10 on 2022-11-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appNegative', '0004_auto_20221117_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coment',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='imgs/logo_perfil.png', upload_to=''),
        ),
    ]
