# Generated by Django 3.2.10 on 2022-11-17 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appNegative', '0005_auto_20221117_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
