# Generated by Django 3.2.10 on 2022-11-17 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appNegative', '0006_remove_profile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coment',
        ),
    ]
