# Generated by Django 3.2.10 on 2022-11-17 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appNegative', '0010_auto_20221117_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
