# Generated by Django 3.2.10 on 2022-11-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appNegative', '0012_comentario_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='logo_.perfil.png', upload_to=''),
        ),
    ]
