# Generated by Django 3.2.10 on 2022-11-17 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appNegative', '0015_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='static/imgs/logo_perfil.png', upload_to=''),
        ),
    ]
